services:
  # Redis
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - rate-limiter
  # Rate Limiter
  rate-limiter:
    container_name: rate-limiter
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - rate-limiter
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=0
    depends_on:
      - redis
networks:
  rate-limiter:
